name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the code
      uses: actions/checkout@v4
     
    - name: Login to Docker Hub
      #env:
       # DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        #DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
       docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
       #Secrets can either be used directly, or can be bound to a env-variable and then be used. Both approach work.
   
    - name: Build the Docker image
      run: |
        docker build --build-arg TMDB_V3_API_KEY=AJ7AYe14eca3e76864yah319b92 -t netflix .
        docker tag netflix kashifahmed/github-action-images:latest
        
    - name: Push Docker image to DockerHub
      run: | 
        docker push kashifahmed/github-action-images:latest
