name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the code
      uses: actions/checkout@v4
     
    - name: Login to Docker Hub
      #env:
       # DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        #DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
       docker login -u ${{env.DOCKER_USERNAME}} -p ${{env.DOCKER_PASSWORD}}
